version: "2.1"
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Check Directory
          command: |
            pwd
            ls -lh
      - python/install-packages:
          pkg-manager: pip
          pre-install-steps:
            - run:
                name: Install dependencies
                command: |
                  cd .docker/python
                  python -m pip install --upgrade pip
workflows:
  main:
    jobs:
      - build
