version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: python --version
      - run:
          name: Check Directory
          command: |
            pwd
            ls -lh
workflows:
  CI-Pipeline:
    jobs:
      - build
