version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: python --version
      - run:
          name: Check Directory
          command: |
            pwd
            ls -lh
      - run:
          name: Install dependencies
          command: |
            cd .docker/python
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Test with pytest
          command: |
            cd code
            pytest
workflows:
  CI-Pipeline:
    jobs:
      - build
