version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Check Directory
          command: |
            pwd
            ls -lh
      - python/install-packages:
          app-dir: .docker/python
          pkg-manager: pip
          pre-install-steps:
            - run:
                name: Install dependencies
                command: |
                  python -m pip install --upgrade pip

workflows:
  main:
    jobs:
      - build
      - python/test:
          app-dir: code
          pip-dependency-file: .docker/python/requirements.txt
