# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t python_cicd .
    - name: export image
      run: |
        mkdir -p /tmp/docker
        docker save python_cicd:latest | gzip > python_cicd.tar.gz
        mv python_cicd.tar.gz /tmp/docker
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python_cicd
        path: /tmp/docker/python_cicd.tar.gz