# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd .docker/python
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd code
        pytest
  push_docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t python_cicd .
    - name: export image
      run: |
        mkdir -p /tmp/docker
        docker save python_cicd:latest | gzip > python_cicd.tar.gz
        mv python_cicd.tar.gz /tmp/docker
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python_cicd
        path: /tmp/docker/python_cicd.tar.gz
  deploy:
    needs: [ push_docker ]
    runs-on: ubuntu-latest
    steps:
    -name: Download artifact
     uses: actions/download-artifact@v3
     with:
       name: python_cicd
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: path/to/artifact