# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd .docker/python
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd code
        pytest
  push_docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t python_cicd .
  # deploy:
  #   needs: [ push_docker ]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: deploy on ec2
  #     env:
  #       PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
  #       HOSTNAME : ${{ secrets.HOSTNAME  }}
  #       USER_NAME : ${{ secrets.USERNAME  }}
  #     run: |
  #       ls -la
  #       echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
  #       ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$HOSTNAME "
  #       docker stop python_cicd || true && docker rm python_cicd || true && docker rmi jugalchanda7/python_cicd:latest || true
  #       docker pull jugalchanda7/python_cicd:latest
  #       docker run -d --name python_cicd -p 5000:8080 jugalchanda7/python_cicd:latest
  #       "